# Generated by Django 6.0.4 on 2026-04-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_TRANSIT', 'In Transit'), ('UNDER_MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
