# Generated by Django 6.0.4 on 2026-04-16 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_location', models.CharField(max_length=200)),
                ('delivery_location', models.CharField(max_length=200)),
                ('cargo_description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver')),
                ('assigned_truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trucks.truck')),
            ],
        ),
    ]
